import { type Post } from "@shared/schema";
import { randomUUID } from "crypto";

export interface IStorage {
  getAllPosts(): Promise<Post[]>;
  getPostsByMonth(month: number): Promise<Post[]>;
  getPostById(id: string): Promise<Post | undefined>;
}

function generateHairExtensionContent(): Post[] {
  const posts: Post[] = [];
  
  const contentData = [
    // January - New Year, Fresh Looks
    { month: 1, day: 1, title: "New Year, New Hair Goals", description: "Inspire your clients with fresh hair transformation ideas for the new year. Share before/after photos of dramatic length changes and encourage bookings for January.", category: "Inspiration", contentType: "Carousel", hashtags: ["#NewYearNewHair", "#HairGoals2025", "#HairExtensions", "#HairTransformation", "#NewYearLook"] },
    { month: 1, day: 3, title: "Winter Hair Care Tips", description: "Educate your audience on how to protect hair extensions during cold, dry winter months. Cover moisturizing tips, static prevention, and nighttime care routines.", category: "Educational", contentType: "Reel", hashtags: ["#WinterHairCare", "#ExtensionCare", "#HairTips", "#HealthyHair", "#WinterBeauty"] },
    { month: 1, day: 5, title: "Meet the Team Monday", description: "Introduce your stylists and their specialties. Show personality and build trust with potential clients by featuring team members and their favorite extension techniques.", category: "Behind the Scenes", contentType: "Video", hashtags: ["#MeetTheTeam", "#HairStylist", "#SalonLife", "#HairArtist", "#TeamTuesday"] },
    { month: 1, day: 7, title: "Length Transformation Reveal", description: "Showcase a stunning before and after of a client going from short to long with seamless extensions. Highlight the natural blend and quality of work.", category: "Before & After", contentType: "Reel", hashtags: ["#HairTransformation", "#BeforeAndAfter", "#LongHair", "#ExtensionSpecialist", "#HairMagic"] },
    { month: 1, day: 9, title: "Extension Method Explained: Tape-Ins", description: "Create an informative post breaking down tape-in extensions - how they work, ideal candidates, maintenance schedule, and longevity expectations.", category: "Educational", contentType: "Carousel", hashtags: ["#TapeInExtensions", "#HairEducation", "#ExtensionMethods", "#HairKnowledge", "#StylistTips"] },
    { month: 1, day: 11, title: "Client Spotlight: Sarah's Journey", description: "Feature a loyal client's hair extension journey over time. Share their story, favorite looks, and testimonial about their experience with your services.", category: "Client Spotlight", contentType: "Video", hashtags: ["#ClientLove", "#HairJourney", "#HappyClient", "#HairStory", "#ClientSpotlight"] },
    { month: 1, day: 13, title: "Weekend Booking Reminder", description: "Encourage last-minute weekend bookings with an engaging post about availability. Include a call-to-action for consultations and touch-up appointments.", category: "Promotional", contentType: "Story", hashtags: ["#BookNow", "#HairAppointment", "#WeekendVibes", "#SalonBooking", "#HairSalon"] },
    { month: 1, day: 15, title: "Poll: Favorite Extension Length", description: "Create an interactive poll asking followers about their preferred extension length. Use results to understand your audience and plan future content.", category: "Engagement", contentType: "Story", hashtags: ["#HairPoll", "#ExtensionLength", "#HairPreferences", "#FollowerFeedback", "#HairCommunity"] },
    { month: 1, day: 17, title: "Blonde Extension Color Matching", description: "Demonstrate the art of matching blonde extension shades to natural hair. Show the importance of undertones and highlight blending techniques.", category: "Educational", contentType: "Reel", hashtags: ["#BlondeHair", "#ColorMatching", "#HairColor", "#ExtensionBlending", "#BlondeExtensions"] },
    { month: 1, day: 19, title: "Styling Tips: Waves with Extensions", description: "Share a quick tutorial on creating beautiful waves with hair extensions. Cover heat protection, sectioning, and finishing techniques.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#HairStyling", "#WavyHair", "#StylingTips", "#HairTutorial", "#BeachWaves"] },
    { month: 1, day: 21, title: "Premium Hair Quality Showcase", description: "Highlight the quality of hair products you use. Show texture, shine, and durability to educate clients on why quality matters for extensions.", category: "Product Showcase", contentType: "Carousel", hashtags: ["#QualityHair", "#PremiumExtensions", "#HairQuality", "#LuxuryHair", "#HairProducts"] },
    { month: 1, day: 23, title: "Extension Removal Process", description: "Demystify the extension removal process with a behind-the-scenes look. Show how gentle and damage-free proper removal can be.", category: "Behind the Scenes", contentType: "Video", hashtags: ["#ExtensionRemoval", "#BehindTheScenes", "#HairCare", "#GentleRemoval", "#SalonProcess"] },
    { month: 1, day: 25, title: "January Special Offer", description: "Announce a limited-time January promotion for new clients. Create urgency with countdown and highlight the value of the offer.", category: "Promotional", contentType: "Photo", hashtags: ["#JanuarySpecial", "#SalonOffer", "#NewClientDiscount", "#HairDeal", "#LimitedOffer"] },
    { month: 1, day: 27, title: "Trending: Curtain Bangs with Extensions", description: "Showcase how to add curtain bangs using extensions for clients who want the look without commitment. Cover styling and blending tips.", category: "Trending", contentType: "Reel", hashtags: ["#CurtainBangs", "#HairTrends", "#BangStyle", "#TrendyHair", "#HairInspo"] },
    { month: 1, day: 29, title: "Q&A: Extension Myths Debunked", description: "Address common misconceptions about hair extensions. Cover topics like damage, maintenance requirements, and longevity in an engaging Q&A format.", category: "Educational", contentType: "Live", hashtags: ["#ExtensionMyths", "#HairFacts", "#QandA", "#HairEducation", "#TruthAboutExtensions"] },
    { month: 1, day: 31, title: "Month-End Transformation Gallery", description: "Compile the best transformations from January into a stunning carousel. Celebrate your work and inspire potential clients.", category: "Before & After", contentType: "Carousel", hashtags: ["#MonthlyTransformations", "#JanuaryRecap", "#HairGallery", "#BeforeAfter", "#HairArtistry"] },
    
    // February - Valentine's, Self-Love
    { month: 2, day: 1, title: "February Self-Love Month", description: "Kick off the month with a message about self-care and treating yourself to the hair you've always wanted. Encourage bookings for Valentine's preparations.", category: "Inspiration", contentType: "Photo", hashtags: ["#SelfLove", "#TreatYourself", "#HairCare", "#FebruaryVibes", "#LoveYourself"] },
    { month: 2, day: 3, title: "Valentine's Day Hair Ideas", description: "Showcase romantic hairstyles perfect for Valentine's Day dates. Include soft waves, elegant updos, and flowing lengths using extensions.", category: "Inspiration", contentType: "Carousel", hashtags: ["#ValentinesHair", "#RomanticHair", "#DateNightHair", "#ValentinesDay", "#HairInspo"] },
    { month: 2, day: 5, title: "Red & Rose Gold Extensions", description: "Feature stunning red and rose gold extension colors perfect for the season of love. Show various shades and how they complement different skin tones.", category: "Product Showcase", contentType: "Reel", hashtags: ["#RedHair", "#RoseGoldHair", "#HairColor", "#ValentinesVibes", "#ColorfulExtensions"] },
    { month: 2, day: 7, title: "Client Love Stories", description: "Share testimonials from clients about how their new hair made them feel confident. Focus on emotional transformations alongside physical ones.", category: "Client Spotlight", contentType: "Video", hashtags: ["#ClientTestimonial", "#ConfidenceBoost", "#HairLove", "#ClientStories", "#HappyClients"] },
    { month: 2, day: 9, title: "Date Night Styling Tutorial", description: "Create a step-by-step tutorial for a glamorous date night look using extensions. Cover volume, curls, and finishing touches.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#DateNight", "#HairTutorial", "#GlamHair", "#StylingTips", "#DateReady"] },
    { month: 2, day: 11, title: "This or That: Extension Styles", description: "Create an engaging interactive post asking followers to choose between different extension styles, lengths, or colors.", category: "Engagement", contentType: "Story", hashtags: ["#ThisOrThat", "#HairPoll", "#ExtensionStyles", "#HairChoice", "#FollowerEngagement"] },
    { month: 2, day: 13, title: "Valentine's Week Special", description: "Announce a Valentine's week promotion for couples or self-love packages. Include consultation and styling services.", category: "Promotional", contentType: "Photo", hashtags: ["#ValentinesSpecial", "#HairPromo", "#CoupleGoals", "#SelfLovePackage", "#BookNow"] },
    { month: 2, day: 14, title: "Happy Valentine's Day", description: "Send love to your clients and followers with a heartfelt Valentine's message. Share appreciation for their support and loyalty.", category: "Engagement", contentType: "Story", hashtags: ["#HappyValentinesDay", "#LoveYourHair", "#ClientLove", "#ValentinesDay", "#ThankYou"] },
    { month: 2, day: 16, title: "Ponytail Extension Transformation", description: "Showcase the power of ponytail extensions for instant glamour. Demonstrate before/after of a sleek, voluminous ponytail.", category: "Before & After", contentType: "Reel", hashtags: ["#PonytailExtension", "#InstantGlam", "#Ponytail", "#HairTransformation", "#QuickStyle"] },
    { month: 2, day: 18, title: "Extension Method: Hand-Tied Wefts", description: "Educate your audience on hand-tied weft extensions - the benefits, installation process, and why they're becoming increasingly popular.", category: "Educational", contentType: "Carousel", hashtags: ["#HandTiedExtensions", "#WeftExtensions", "#ExtensionEducation", "#HairMethods", "#PremiumExtensions"] },
    { month: 2, day: 20, title: "Salon Tour: Where Magic Happens", description: "Give followers a virtual tour of your salon space. Show the ambiance, products, and tools that create beautiful transformations.", category: "Behind the Scenes", contentType: "Video", hashtags: ["#SalonTour", "#BehindTheScenes", "#SalonLife", "#HairSalon", "#OurSpace"] },
    { month: 2, day: 22, title: "Bridal Hair Consultation Tips", description: "Share advice for brides-to-be considering extensions for their wedding day. Cover timeline, trials, and what to expect.", category: "Tips & Tricks", contentType: "Carousel", hashtags: ["#BridalHair", "#WeddingHair", "#BrideToBe", "#WeddingPlanning", "#BridalExtensions"] },
    { month: 2, day: 24, title: "Dimensional Brunette Extensions", description: "Showcase the beauty of dimensional brunette extensions with lowlights and highlights. Demonstrate color blending techniques.", category: "Product Showcase", contentType: "Reel", hashtags: ["#BrunetteHair", "#DimensionalColor", "#BrownHair", "#HairColor", "#NaturalLooking"] },
    { month: 2, day: 26, title: "Extension Care Product Favorites", description: "Share your recommended products for extension care - shampoos, conditioners, oils, and tools that keep extensions looking their best.", category: "Product Showcase", contentType: "Carousel", hashtags: ["#HairProducts", "#ExtensionCare", "#ProductRecommendations", "#HairCareTips", "#MustHaves"] },
    { month: 2, day: 28, title: "February Favorites Recap", description: "Share the most popular looks and transformations from February. Celebrate the month's successes and client wins.", category: "Before & After", contentType: "Carousel", hashtags: ["#FebruaryRecap", "#MonthlyFavorites", "#HairHighlights", "#ClientTransformations", "#BestOf"] },
    
    // March - Spring, Renewal
    { month: 3, day: 1, title: "Spring Hair Refresh", description: "Welcome spring with fresh hair inspiration. Encourage clients to update their look with new extensions, colors, or lengths for the season.", category: "Inspiration", contentType: "Carousel", hashtags: ["#SpringHair", "#HairRefresh", "#NewSeason", "#SpringVibes", "#FreshLook"] },
    { month: 3, day: 3, title: "Honey Blonde Spring Trend", description: "Showcase the trending honey blonde shade perfect for spring. Demonstrate how extensions can add dimension and warmth.", category: "Trending", contentType: "Reel", hashtags: ["#HoneyBlonde", "#SpringTrends", "#BlondeHair", "#WarmTones", "#TrendyHair"] },
    { month: 3, day: 5, title: "St. Patrick's Day Hair Inspo", description: "Fun festive content featuring green accessories or styling ideas for St. Patrick's Day celebrations.", category: "Inspiration", contentType: "Story", hashtags: ["#StPatricksDay", "#FestiveHair", "#GreenVibes", "#HolidayHair", "#PartyReady"] },
    { month: 3, day: 7, title: "Volume Without Extensions Tutorial", description: "Share styling tips for clients between appointments. Show how to maximize volume with techniques that complement their extensions.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#VolumeHair", "#StylingTips", "#HairHacks", "#BigHair", "#VolumeTricks"] },
    { month: 3, day: 9, title: "Client Transformation: Length Goals", description: "Feature a dramatic length transformation with detailed before/after photos. Share the client's hair journey story.", category: "Before & After", contentType: "Carousel", hashtags: ["#LengthGoals", "#HairTransformation", "#LongHairDontCare", "#BeforeAfter", "#DramaticChange"] },
    { month: 3, day: 11, title: "Extension Consultation: What to Expect", description: "Walk potential clients through the consultation process. Cover questions asked, assessment done, and recommendations made.", category: "Educational", contentType: "Video", hashtags: ["#HairConsultation", "#ExtensionJourney", "#FirstAppointment", "#WhatToExpect", "#ClientCare"] },
    { month: 3, day: 13, title: "Spring Cleaning: Hair Edition", description: "Share tips on refreshing extension care routines for spring. Cover deep conditioning, detangling, and storage tips.", category: "Tips & Tricks", contentType: "Carousel", hashtags: ["#SpringCleaning", "#HairCare", "#ExtensionMaintenance", "#DeepCondition", "#HairRoutine"] },
    { month: 3, day: 15, title: "Ask Me Anything: Extensions", description: "Host a live Q&A session answering follower questions about extensions. Cover common concerns and provide expert advice.", category: "Engagement", contentType: "Live", hashtags: ["#AMA", "#ExtensionQuestions", "#LiveQA", "#HairExpert", "#AskMe"] },
    { month: 3, day: 17, title: "Lucky St. Patrick's Day", description: "Share festive St. Patrick's Day wishes with your community. Include fun hair styling ideas for celebrating.", category: "Engagement", contentType: "Story", hashtags: ["#HappyStPatricksDay", "#Lucky", "#CelebrationHair", "#FestiveVibes", "#GreenDay"] },
    { month: 3, day: 19, title: "Balayage Extensions Tutorial", description: "Showcase how to install and blend balayage extensions for a seamless, natural-looking result.", category: "Educational", contentType: "Reel", hashtags: ["#Balayage", "#BalayageExtensions", "#BlendedHair", "#NaturalLook", "#ColorTechnique"] },
    { month: 3, day: 21, title: "First Day of Spring Celebration", description: "Celebrate the official start of spring with bright, fresh content. Encourage new beginnings with new hair looks.", category: "Inspiration", contentType: "Photo", hashtags: ["#FirstDayOfSpring", "#SpringEquinox", "#NewBeginnings", "#FreshStart", "#SpringHair"] },
    { month: 3, day: 23, title: "Weekend Glam: Extensions Styling", description: "Share quick weekend styling ideas for extension clients. Focus on effortless yet glamorous looks.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#WeekendGlam", "#EasyStyles", "#QuickHair", "#WeekendVibes", "#GlamHair"] },
    { month: 3, day: 25, title: "Product Deep Dive: Bonding Products", description: "Educate on the importance of quality bonding products for extension longevity and hair health.", category: "Product Showcase", contentType: "Carousel", hashtags: ["#ExtensionBonds", "#HairProducts", "#QualityMatters", "#ExtensionCare", "#ProductEducation"] },
    { month: 3, day: 27, title: "Client Appreciation Post", description: "Show gratitude to your loyal clients with a heartfelt appreciation post. Feature multiple client photos with their permission.", category: "Client Spotlight", contentType: "Carousel", hashtags: ["#ClientAppreciation", "#ThankYou", "#LoyalClients", "#Grateful", "#BestClients"] },
    { month: 3, day: 29, title: "Spring Break Hair Prep", description: "Help clients prepare their extensions for spring break vacations. Cover travel tips, beach care, and styling ideas.", category: "Tips & Tricks", contentType: "Carousel", hashtags: ["#SpringBreak", "#VacationHair", "#TravelTips", "#BeachHair", "#HolidayReady"] },
    { month: 3, day: 31, title: "March Transformation Gallery", description: "Compile the best spring transformations from March. Celebrate seasonal changes and beautiful results.", category: "Before & After", contentType: "Carousel", hashtags: ["#MarchRecap", "#SpringTransformations", "#MonthlyBest", "#HairGallery", "#BeforeAfter"] },
    
    // April - Fresh starts, Easter
    { month: 4, day: 1, title: "April Fresh Starts", description: "Welcome April with inspiration for new hair journeys. Encourage clients to take the leap with extensions they've been considering.", category: "Inspiration", contentType: "Photo", hashtags: ["#AprilVibes", "#FreshStart", "#NewHair", "#HairJourney", "#SpringHair"] },
    { month: 4, day: 3, title: "Pastel Extensions for Spring", description: "Showcase beautiful pastel extension colors perfect for spring - lavender, rose, mint. Ideal for creative clients.", category: "Product Showcase", contentType: "Carousel", hashtags: ["#PastelHair", "#SpringColors", "#ColorfulExtensions", "#UniqueHair", "#PastelVibes"] },
    { month: 4, day: 5, title: "Extension Maintenance Schedule", description: "Create an educational guide on maintenance schedules for different extension types. Help clients understand care timelines.", category: "Educational", contentType: "Carousel", hashtags: ["#ExtensionMaintenance", "#HairCareSchedule", "#MaintenanceTips", "#ExtensionCare", "#HealthyExtensions"] },
    { month: 4, day: 7, title: "Client Journey: 1 Year with Extensions", description: "Feature a client's one-year extension journey. Show progression, different styles, and their experience over time.", category: "Client Spotlight", contentType: "Video", hashtags: ["#ExtensionJourney", "#OneYear", "#ClientStory", "#HairEvolution", "#LongTermClient"] },
    { month: 4, day: 9, title: "Fusion Extensions Explained", description: "Deep dive into fusion (keratin bond) extensions - pros, cons, ideal candidates, and what sets them apart from other methods.", category: "Educational", contentType: "Reel", hashtags: ["#FusionExtensions", "#KeratinBonds", "#ExtensionMethods", "#HairEducation", "#PremiumExtensions"] },
    { month: 4, day: 11, title: "Spring Wedding Hair Preview", description: "Showcase bridal extension styles for spring weddings. Feature romantic, soft looks perfect for the season.", category: "Inspiration", contentType: "Carousel", hashtags: ["#SpringWedding", "#BridalHair", "#WeddingSeason", "#BrideHair", "#WeddingInspiration"] },
    { month: 4, day: 13, title: "Easter Hair Inspiration", description: "Share festive Easter-themed hair content with spring colors and accessories. Fun, seasonal engagement content.", category: "Engagement", contentType: "Story", hashtags: ["#EasterHair", "#SpringVibes", "#EasterWeekend", "#FestiveHair", "#HolidayStyle"] },
    { month: 4, day: 15, title: "Studio Setup: Where We Create", description: "Show your workspace setup - tools, organization, and how you prepare for each client appointment.", category: "Behind the Scenes", contentType: "Video", hashtags: ["#StudioSetup", "#BehindTheScenes", "#SalonPrep", "#WorkspaceGoals", "#HairStudio"] },
    { month: 4, day: 17, title: "Sleek Straight Extension Styling", description: "Tutorial on achieving sleek, straight looks with extensions. Cover heat protection, sectioning, and finishing products.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#SleekHair", "#StraightHair", "#StylingTutorial", "#SleekAndShiny", "#HairTips"] },
    { month: 4, day: 19, title: "Volume Transformation Saturday", description: "Showcase a dramatic volume transformation - thin to thick hair using extensions. Highlight the confidence boost.", category: "Before & After", contentType: "Reel", hashtags: ["#VolumeTransformation", "#ThinToThick", "#HairVolume", "#ConfidenceBoost", "#SaturdayTransformation"] },
    { month: 4, day: 21, title: "Earth Day: Sustainable Hair Care", description: "Share tips on sustainable extension care and eco-friendly products. Highlight any sustainable practices in your business.", category: "Educational", contentType: "Carousel", hashtags: ["#EarthDay", "#SustainableBeauty", "#EcoFriendly", "#GreenBeauty", "#SustainableHairCare"] },
    { month: 4, day: 23, title: "Extension Types Comparison", description: "Create a comprehensive comparison of extension methods available. Help potential clients understand their options.", category: "Educational", contentType: "Carousel", hashtags: ["#ExtensionComparison", "#ExtensionTypes", "#HairOptions", "#ChooseYourMethod", "#ExtensionGuide"] },
    { month: 4, day: 25, title: "Client Poll: Dream Hair Color", description: "Engage followers with an interactive poll about their dream hair color for spring and summer seasons.", category: "Engagement", contentType: "Story", hashtags: ["#HairPoll", "#DreamHair", "#ColorChoice", "#FollowerEngagement", "#HairColor"] },
    { month: 4, day: 27, title: "Sunday Self-Care Hair Routine", description: "Share a relaxing Sunday hair care routine for extension clients. Focus on maintenance and self-care.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#SundaySelfCare", "#HairRoutine", "#SelfCareSunday", "#RelaxingRoutine", "#ExtensionCare"] },
    { month: 4, day: 29, title: "Spring Special Announcement", description: "Announce a spring promotion or new service offering. Create excitement and encourage bookings.", category: "Promotional", contentType: "Photo", hashtags: ["#SpringSpecial", "#NewOffer", "#SalonPromo", "#BookNow", "#LimitedTime"] },
    { month: 4, day: 30, title: "April Highlights Reel", description: "Compile the month's best moments, transformations, and client wins into an engaging highlights reel.", category: "Before & After", contentType: "Reel", hashtags: ["#AprilHighlights", "#MonthlyRecap", "#BestMoments", "#HairHighlights", "#TransformationReel"] },
    
    // May - Mother's Day, Spring Beauty
    { month: 5, day: 1, title: "May Day Hair Celebration", description: "Welcome May with celebration of spring beauty. Feature fresh, floral-inspired hair looks and styling ideas.", category: "Inspiration", contentType: "Carousel", hashtags: ["#MayDay", "#SpringBeauty", "#FloralVibes", "#FreshHair", "#MayFlowers"] },
    { month: 5, day: 3, title: "Mother's Day Gift Guide", description: "Create a gift guide featuring extension services and packages perfect for Mother's Day gifts.", category: "Promotional", contentType: "Carousel", hashtags: ["#MothersDay", "#GiftGuide", "#GiftForMom", "#SalonGift", "#TreatMom"] },
    { month: 5, day: 5, title: "Glamorous Mom Makeover", description: "Feature a mom transformation with extensions. Show the confidence and joy of refreshed, beautiful hair.", category: "Before & After", contentType: "Video", hashtags: ["#MomMakeover", "#Transformation", "#MomGlam", "#BeforeAfter", "#BeautifulMom"] },
    { month: 5, day: 7, title: "Extension Care for Busy Moms", description: "Share quick and easy maintenance tips for busy moms with extensions. Focus on time-saving techniques.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#BusyMom", "#QuickTips", "#MomLife", "#EasyHairCare", "#TimeSaver"] },
    { month: 5, day: 9, title: "Mother-Daughter Hair Goals", description: "Feature mother-daughter duo transformations or matching hair moments. Celebrate the special bond.", category: "Client Spotlight", contentType: "Carousel", hashtags: ["#MotherDaughter", "#HairGoals", "#FamilyHair", "#MatchingHair", "#SpecialBond"] },
    { month: 5, day: 11, title: "Happy Mother's Day", description: "Send heartfelt Mother's Day wishes to all the amazing moms in your community. Celebrate their beauty.", category: "Engagement", contentType: "Photo", hashtags: ["#HappyMothersDay", "#CelebrateMom", "#MomLove", "#Gratitude", "#SpecialDay"] },
    { month: 5, day: 13, title: "Summer-Ready Hair Prep", description: "Start preparing clients for summer with tips on maintaining extensions in heat and humidity.", category: "Educational", contentType: "Carousel", hashtags: ["#SummerReady", "#HeatProtection", "#SummerHairCare", "#SeasonalTips", "#ExtensionPrep"] },
    { month: 5, day: 15, title: "Beachy Waves Tutorial", description: "Create a tutorial for achieving perfect beachy waves with extensions. Cover techniques and products.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#BeachyWaves", "#SummerHair", "#WavesTutorial", "#BeachVibes", "#HairStyling"] },
    { month: 5, day: 17, title: "Highlight Extensions Demo", description: "Demonstrate how to add dimension with highlight extensions. Show the blending process and final result.", category: "Educational", contentType: "Video", hashtags: ["#HighlightExtensions", "#Dimension", "#HairColor", "#BlendingTechnique", "#NaturalHighlights"] },
    { month: 5, day: 19, title: "Weekend Transformation Reveal", description: "Reveal an amazing weekend transformation. Build anticipation with before teaser and dramatic after reveal.", category: "Before & After", contentType: "Reel", hashtags: ["#WeekendTransformation", "#DramaticReveal", "#BeforeAfter", "#HairMagic", "#TransformationSaturday"] },
    { month: 5, day: 21, title: "Client Q&A Session", description: "Answer pre-submitted client questions about extensions, care, and styling. Build community engagement.", category: "Engagement", contentType: "Live", hashtags: ["#ClientQA", "#LiveSession", "#AskAnything", "#ExtensionQuestions", "#CommunityChat"] },
    { month: 5, day: 23, title: "Copper Tones for Summer", description: "Showcase trending copper and auburn extension shades perfect for the upcoming summer season.", category: "Trending", contentType: "Carousel", hashtags: ["#CopperHair", "#AuburnHair", "#SummerTrends", "#WarmTones", "#TrendyColor"] },
    { month: 5, day: 25, title: "Memorial Day Weekend Styles", description: "Share quick and easy styles perfect for Memorial Day weekend festivities and outdoor events.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#MemorialDayWeekend", "#HolidayHair", "#QuickStyles", "#WeekendReady", "#OutdoorHair"] },
    { month: 5, day: 27, title: "Salon Day: Full Process Video", description: "Take followers through a complete extension appointment from start to finish. Show the full experience.", category: "Behind the Scenes", contentType: "Video", hashtags: ["#SalonDay", "#FullProcess", "#BehindTheScenes", "#ExtensionAppointment", "#ClientExperience"] },
    { month: 5, day: 29, title: "Product Favorites: Summer Edition", description: "Share must-have products for summer extension care - UV protectants, hydrating treatments, and styling products.", category: "Product Showcase", contentType: "Carousel", hashtags: ["#SummerProducts", "#MustHaves", "#ExtensionCare", "#SeasonalFavorites", "#ProductGuide"] },
    { month: 5, day: 31, title: "May Transformation Montage", description: "Compile May's best transformations into an inspiring montage. Celebrate the month's beautiful work.", category: "Before & After", contentType: "Reel", hashtags: ["#MayMontage", "#TransformationReel", "#MonthlyBest", "#HairGallery", "#BeforeAfterMay"] },
    
    // June - Summer, Weddings
    { month: 6, day: 1, title: "Hello Summer Hair", description: "Welcome the official start of summer with sun-kissed hair inspiration. Feature blonde highlights and beachy textures.", category: "Inspiration", contentType: "Carousel", hashtags: ["#SummerHair", "#HelloSummer", "#SunKissed", "#BeachyHair", "#SummerVibes"] },
    { month: 6, day: 3, title: "Wedding Season Prep Guide", description: "Create a comprehensive guide for brides and wedding guests preparing their extension looks for the season.", category: "Educational", contentType: "Carousel", hashtags: ["#WeddingSeason", "#BridalPrep", "#WeddingGuest", "#WeddingHair", "#SeasonGuide"] },
    { month: 6, day: 5, title: "Bridal Transformation Feature", description: "Showcase a stunning bridal extension transformation. Highlight the journey from consultation to wedding day.", category: "Before & After", contentType: "Video", hashtags: ["#BridalTransformation", "#WeddingDay", "#BrideBeauty", "#BeforeAfter", "#BridalHair"] },
    { month: 6, day: 7, title: "Summer Hair Color Trends", description: "Feature the hottest summer hair color trends incorporating extensions - babylights, money pieces, and sun-kissed looks.", category: "Trending", contentType: "Reel", hashtags: ["#SummerColorTrends", "#Babylights", "#MoneyPiece", "#TrendyHair", "#ColorTrends2025"] },
    { month: 6, day: 9, title: "Pool Party Hair Prep", description: "Share tips on protecting extensions at pool parties. Cover chlorine protection, styling, and after-swim care.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#PoolParty", "#ChlorineProtection", "#SummerTips", "#SwimHair", "#PartyReady"] },
    { month: 6, day: 11, title: "Client Spotlight: Summer Bride", description: "Feature a summer bride client and her extension journey. Share her story and wedding day look.", category: "Client Spotlight", contentType: "Carousel", hashtags: ["#SummerBride", "#BridalStory", "#ClientFeature", "#WeddingHair", "#HappyBride"] },
    { month: 6, day: 13, title: "Halfway Through the Year Check", description: "Reflect on the year so far with favorite transformations and client wins. Encourage followers to share their hair goals.", category: "Engagement", contentType: "Carousel", hashtags: ["#MidYearCheck", "#HalfwayThere", "#HairGoals", "#YearReview", "#Reflection"] },
    { month: 6, day: 15, title: "Father's Day Gift Cards", description: "Promote gift cards for Father's Day - perfect for wives and daughters who want to treat themselves.", category: "Promotional", contentType: "Story", hashtags: ["#FathersDay", "#GiftCard", "#TreatYourself", "#SalonGift", "#HairGift"] },
    { month: 6, day: 17, title: "Vacation Hair Survival Guide", description: "Comprehensive guide for maintaining extensions during summer vacations - packing tips, care routine, and travel essentials.", category: "Educational", contentType: "Carousel", hashtags: ["#VacationHair", "#TravelTips", "#SummerVacation", "#ExtensionTravel", "#SurvivalGuide"] },
    { month: 6, day: 19, title: "Summer Solstice Celebration", description: "Celebrate the longest day of the year with bright, radiant hair content. Share golden hour styling photos.", category: "Inspiration", contentType: "Photo", hashtags: ["#SummerSolstice", "#LongestDay", "#GoldenHour", "#SunnyHair", "#SolsticeCelebration"] },
    { month: 6, day: 21, title: "Clip-In Extensions for Events", description: "Showcase the versatility of clip-in extensions for special events. Perfect for brides, bridesmaids, and guests.", category: "Product Showcase", contentType: "Reel", hashtags: ["#ClipInExtensions", "#EventHair", "#TemporaryGlam", "#SpecialOccasion", "#InstantVolume"] },
    { month: 6, day: 23, title: "Behind the Scenes: Wedding Prep", description: "Show behind-the-scenes preparation for a wedding day hair appointment. Capture the excitement and process.", category: "Behind the Scenes", contentType: "Video", hashtags: ["#WeddingPrep", "#BehindTheScenes", "#BridalMorning", "#WeddingDay", "#HairPrep"] },
    { month: 6, day: 25, title: "Summer Blonde Goals", description: "Feature stunning summer blonde transformations. Show different blonde shades and how extensions achieve the perfect look.", category: "Before & After", contentType: "Carousel", hashtags: ["#SummerBlonde", "#BlondeGoals", "#GoldenBlonde", "#BlondeTransformation", "#BeachBlonde"] },
    { month: 6, day: 27, title: "Quick Summer Styles", description: "Share five quick and easy summer hairstyles for extension clients. Focus on heat-friendly and vacation-ready looks.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#QuickStyles", "#SummerHairstyles", "#EasyHair", "#VacationStyles", "#HairInspiration"] },
    { month: 6, day: 29, title: "End of Month Special", description: "Announce an end-of-month booking special for July appointments. Create urgency for summer consultations.", category: "Promotional", contentType: "Photo", hashtags: ["#MonthEndSpecial", "#JulyBookings", "#SummerSpecial", "#BookNow", "#LimitedOffer"] },
    { month: 6, day: 30, title: "June Highlights Gallery", description: "Celebrate June with a gallery of the month's best transformations, weddings, and client wins.", category: "Before & After", contentType: "Carousel", hashtags: ["#JuneHighlights", "#MonthlyRecap", "#SummerGallery", "#BestOfJune", "#TransformationGallery"] },
    
    // July - Summer Peak, Independence Day
    { month: 7, day: 1, title: "July Hair Goals", description: "Kick off July with summer hair inspiration. Encourage clients to embrace bold summer looks and transformations.", category: "Inspiration", contentType: "Carousel", hashtags: ["#JulyHair", "#SummerGoals", "#MidSummer", "#HairInspo", "#JulyVibes"] },
    { month: 7, day: 3, title: "4th of July Hair Ideas", description: "Share festive red, white, and blue hair accessory ideas and patriotic styling for Independence Day celebrations.", category: "Inspiration", contentType: "Story", hashtags: ["#4thOfJuly", "#PatrioticHair", "#IndependenceDay", "#FestiveHair", "#RedWhiteBlue"] },
    { month: 7, day: 4, title: "Happy 4th of July", description: "Celebrate Independence Day with festive wishes to your community. Share holiday-themed content and styling ideas.", category: "Engagement", contentType: "Photo", hashtags: ["#Happy4thOfJuly", "#IndependenceDay", "#Celebrate", "#USA", "#HolidayVibes"] },
    { month: 7, day: 6, title: "Heat Protection for Extensions", description: "Essential guide on protecting extensions from summer heat - heat styling tips, UV protection, and outdoor care.", category: "Educational", contentType: "Carousel", hashtags: ["#HeatProtection", "#SummerCare", "#ExtensionProtection", "#UVDamage", "#HairHealth"] },
    { month: 7, day: 8, title: "Summer Concert Hair", description: "Share festival and concert-ready hairstyles using extensions. Focus on fun, creative looks that last all day.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#ConcertHair", "#FestivalStyle", "#SummerFestival", "#MusicFestival", "#PartyHair"] },
    { month: 7, day: 10, title: "Client Transformation: Beach Ready", description: "Feature a stunning beach-ready transformation. Show sun-kissed color and effortless summer styling.", category: "Before & After", contentType: "Reel", hashtags: ["#BeachReady", "#SummerTransformation", "#BeforeAfter", "#SunKissedHair", "#VacationReady"] },
    { month: 7, day: 12, title: "I-Tip Extensions Deep Dive", description: "Educate on I-tip (micro-ring) extensions - benefits, installation process, ideal candidates, and care requirements.", category: "Educational", contentType: "Video", hashtags: ["#ITipExtensions", "#MicroRing", "#ExtensionEducation", "#HairMethods", "#DetailedGuide"] },
    { month: 7, day: 14, title: "Mid-Summer Check-In", description: "Interactive check-in asking followers about their summer hair journey and goals for the rest of the season.", category: "Engagement", contentType: "Story", hashtags: ["#MidSummerCheck", "#HairJourney", "#FollowerChat", "#SummerGoals", "#CommunityCheck"] },
    { month: 7, day: 16, title: "Protective Summer Styles", description: "Share protective hairstyles for summer that keep extensions secure and minimize heat damage.", category: "Tips & Tricks", contentType: "Carousel", hashtags: ["#ProtectiveStyles", "#SummerProtection", "#HairHealth", "#StyleAndProtect", "#ExtensionCare"] },
    { month: 7, day: 18, title: "Salon Vibes: Day in the Life", description: "Share a day-in-the-life at the salon during busy summer season. Show the energy and transformations.", category: "Behind the Scenes", contentType: "Video", hashtags: ["#DayInTheLife", "#SalonVibes", "#SummerBusy", "#BehindTheScenes", "#SalonLife"] },
    { month: 7, day: 20, title: "Sunset Hair Photoshoot", description: "Feature golden hour photos showcasing how extensions look in beautiful natural lighting.", category: "Inspiration", contentType: "Carousel", hashtags: ["#SunsetHair", "#GoldenHour", "#HairPhotoshoot", "#NaturalLight", "#HairGoals"] },
    { month: 7, day: 22, title: "Extension FAQ Roundup", description: "Answer the most frequently asked questions about extensions in one comprehensive post.", category: "Educational", contentType: "Carousel", hashtags: ["#ExtensionFAQ", "#CommonQuestions", "#HairAnswers", "#ClientQuestions", "#KnowBeforeYouGo"] },
    { month: 7, day: 24, title: "Summer Color Correction", description: "Show a color correction transformation using extensions to achieve the perfect summer look after failed DIY attempts.", category: "Before & After", contentType: "Reel", hashtags: ["#ColorCorrection", "#HairRescue", "#FixMyHair", "#Transformation", "#ColorFix"] },
    { month: 7, day: 26, title: "Quick Updo with Extensions", description: "Tutorial on creating elegant updos with extensions. Perfect for summer events and weddings.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#Updo", "#ElegantHair", "#QuickUpdo", "#EventHair", "#StylingTutorial"] },
    { month: 7, day: 28, title: "Client Love: Testimonial Tuesday", description: "Share heartfelt client testimonials about their extension experience. Build trust with potential clients.", category: "Client Spotlight", contentType: "Carousel", hashtags: ["#TestimonialTuesday", "#ClientLove", "#Reviews", "#HappyClients", "#RealResults"] },
    { month: 7, day: 30, title: "End of July Celebration", description: "Celebrate the end of July with a compilation of the month's best moments and transformations.", category: "Before & After", contentType: "Reel", hashtags: ["#JulyRecap", "#MonthEnd", "#SummerHighlights", "#BestOfJuly", "#TransformationReel"] },
    
    // August - Back to School, Late Summer
    { month: 8, day: 1, title: "August Fresh Starts", description: "Welcome August with back-to-school and fresh start energy. Inspire clients to refresh their look for the new season.", category: "Inspiration", contentType: "Photo", hashtags: ["#AugustVibes", "#FreshStart", "#NewMonth", "#HairRefresh", "#LateSummer"] },
    { month: 8, day: 3, title: "Back to School Hair Guide", description: "Create a guide for students and teachers refreshing their hair for back-to-school season.", category: "Educational", contentType: "Carousel", hashtags: ["#BackToSchool", "#StudentHair", "#TeacherStyle", "#SchoolReady", "#FallPrep"] },
    { month: 8, day: 5, title: "Teacher Transformation", description: "Feature a teacher getting ready for the new school year with a stunning extension transformation.", category: "Before & After", contentType: "Video", hashtags: ["#TeacherTransformation", "#BackToSchool", "#TeacherLife", "#BeforeAfter", "#ConfidentTeacher"] },
    { month: 8, day: 7, title: "Low-Maintenance Extension Styles", description: "Share easy, low-maintenance styles perfect for busy schedules during back-to-school season.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#LowMaintenance", "#EasyStyles", "#BusyLife", "#QuickHair", "#SimpleStyles"] },
    { month: 8, day: 9, title: "End of Summer Sale", description: "Announce an end-of-summer promotion for clients wanting to refresh their look before fall.", category: "Promotional", contentType: "Photo", hashtags: ["#EndOfSummerSale", "#SummerSpecial", "#LastChance", "#BookNow", "#SummerSavings"] },
    { month: 8, day: 11, title: "Transitioning Summer to Fall Hair", description: "Guide clients on transitioning their hair color and style from summer brightness to fall warmth.", category: "Educational", contentType: "Carousel", hashtags: ["#SummerToFall", "#SeasonTransition", "#HairColor", "#FallPrep", "#ChangingSeason"] },
    { month: 8, day: 13, title: "Client Poll: Fall Hair Plans", description: "Engage followers with a poll about their fall hair plans - color changes, length additions, or new styles.", category: "Engagement", contentType: "Story", hashtags: ["#FallHairPoll", "#HairPlans", "#FollowerEngagement", "#FallGoals", "#HairVote"] },
    { month: 8, day: 15, title: "Rich Brunette for Fall Preview", description: "Preview rich, deep brunette shades perfect for the upcoming fall season. Show dimension and depth with extensions.", category: "Trending", contentType: "Carousel", hashtags: ["#RichBrunette", "#FallPreview", "#DeepBrown", "#FallColors", "#BrunetteGoals"] },
    { month: 8, day: 17, title: "Weekend Transformation Marathon", description: "Feature multiple weekend transformations in one engaging reel. Show the variety of work done.", category: "Before & After", contentType: "Reel", hashtags: ["#WeekendTransformations", "#TransformationMarathon", "#BeforeAfter", "#BusyWeekend", "#HairMagic"] },
    { month: 8, day: 19, title: "Extension Longevity Tips", description: "Share pro tips on maximizing the lifespan of extensions. Cover care routines, products, and habits to avoid.", category: "Tips & Tricks", contentType: "Carousel", hashtags: ["#ExtensionLongevity", "#ProTips", "#LastLonger", "#ExtensionCare", "#HairInvestment"] },
    { month: 8, day: 21, title: "Salon Updates & New Services", description: "Announce any new services, products, or updates at your salon for the upcoming fall season.", category: "Promotional", contentType: "Photo", hashtags: ["#SalonNews", "#NewServices", "#FallUpdates", "#Announcement", "#ComingSoon"] },
    { month: 8, day: 23, title: "First Day of School Looks", description: "Share first-day-of-school worthy hairstyles for students at all levels. Focus on polished, confident looks.", category: "Inspiration", contentType: "Reel", hashtags: ["#FirstDayOfSchool", "#SchoolHair", "#StudentStyle", "#BackToSchool", "#ConfidentStart"] },
    { month: 8, day: 25, title: "Client Journey: Summer Recap", description: "Feature a client's summer hair journey - from initial transformation through summer adventures.", category: "Client Spotlight", contentType: "Video", hashtags: ["#SummerJourney", "#ClientStory", "#SummerRecap", "#HairEvolution", "#SeasonHighlight"] },
    { month: 8, day: 27, title: "Damage Repair with Extensions", description: "Showcase how extensions can provide a solution while damaged hair grows out healthy. Focus on hair health.", category: "Educational", contentType: "Carousel", hashtags: ["#DamageRepair", "#HairHealth", "#GrowOut", "#HealthyHair", "#ExtensionSolution"] },
    { month: 8, day: 29, title: "Labor Day Weekend Prep", description: "Share styling ideas and care tips for Labor Day weekend activities and end-of-summer celebrations.", category: "Tips & Tricks", contentType: "Story", hashtags: ["#LaborDayWeekend", "#EndOfSummer", "#WeekendPrep", "#HolidayReady", "#LastHurrah"] },
    { month: 8, day: 31, title: "August Highlights & Goodbye Summer", description: "Bid farewell to summer with a compilation of August's best transformations and memorable moments.", category: "Before & After", contentType: "Carousel", hashtags: ["#AugustHighlights", "#GoodbyeSummer", "#MonthlyRecap", "#SummerEnd", "#BestOfAugust"] },
    
    // September - Fall, New Beginnings
    { month: 9, day: 1, title: "Hello Fall Hair Season", description: "Welcome the fall season with warm, cozy hair inspiration. Feature autumnal colors and rich tones.", category: "Inspiration", contentType: "Carousel", hashtags: ["#FallHair", "#AutumnVibes", "#HelloFall", "#WarmTones", "#FallColors"] },
    { month: 9, day: 3, title: "Labor Day Celebration", description: "Celebrate Labor Day with appreciation for your hardworking team and clients. Share holiday wishes.", category: "Engagement", contentType: "Photo", hashtags: ["#LaborDay", "#HappyLaborDay", "#ThankYou", "#Celebrate", "#TeamAppreciation"] },
    { month: 9, day: 5, title: "Fall Color Trends Guide", description: "Comprehensive guide to fall hair color trends - copper, auburn, chocolate, and caramel tones with extensions.", category: "Trending", contentType: "Carousel", hashtags: ["#FallColorTrends", "#AutumnColors", "#Copper", "#Auburn", "#TrendGuide"] },
    { month: 9, day: 7, title: "Cozy Fall Transformation", description: "Feature a stunning fall transformation with warm, rich colors perfect for the season.", category: "Before & After", contentType: "Reel", hashtags: ["#FallTransformation", "#WarmColors", "#CozyVibes", "#BeforeAfter", "#AutumnGlow"] },
    { month: 9, day: 9, title: "Extension Care for Changing Weather", description: "Guide clients on adjusting their extension care routine as weather changes from summer to fall.", category: "Educational", contentType: "Carousel", hashtags: ["#SeasonalCare", "#WeatherChange", "#FallCareTips", "#ExtensionRoutine", "#AdaptYourCare"] },
    { month: 9, day: 11, title: "Fall Wedding Hair Showcase", description: "Feature autumnal wedding hairstyles with extensions. Show romantic, elegant fall bridal looks.", category: "Inspiration", contentType: "Carousel", hashtags: ["#FallWedding", "#AutumnBride", "#WeddingHair", "#FallBridal", "#WeddingSeason"] },
    { month: 9, day: 13, title: "Friday the 13th Fun", description: "Fun, spooky-themed hair content for Friday the 13th. Keep it playful and on-brand.", category: "Engagement", contentType: "Story", hashtags: ["#FridayThe13th", "#SpookyHair", "#FunFriday", "#PlayfulContent", "#Superstition"] },
    { month: 9, day: 15, title: "Client Spotlight: Career Woman", description: "Feature a professional woman client and how extensions boost her confidence in her career.", category: "Client Spotlight", contentType: "Video", hashtags: ["#CareerWoman", "#ProfessionalHair", "#ConfidentWoman", "#ClientFeature", "#WorkplaceStyle"] },
    { month: 9, day: 17, title: "Silk Press with Extensions", description: "Showcase the beautiful results of silk press styling with extensions on textured hair.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#SilkPress", "#TexturedHair", "#SmoothStyle", "#ExtensionStyling", "#SleekFinish"] },
    { month: 9, day: 19, title: "Fall Equinox Celebration", description: "Celebrate the first official day of fall with seasonal inspiration and gratitude for the community.", category: "Inspiration", contentType: "Photo", hashtags: ["#FallEquinox", "#FirstDayOfFall", "#AutumnBegins", "#SeasonalCelebration", "#FallVibes"] },
    { month: 9, day: 21, title: "Weft Extension Comparison", description: "Compare different types of weft extensions - machine weft, hand-tied, hybrid. Help clients choose.", category: "Educational", contentType: "Carousel", hashtags: ["#WeftExtensions", "#ExtensionComparison", "#HandTied", "#MachineWeft", "#ChooseWisely"] },
    { month: 9, day: 23, title: "Autumn Ombre Ideas", description: "Showcase beautiful autumn ombre and balayage looks using extensions. Feature warm, gradient colors.", category: "Product Showcase", contentType: "Carousel", hashtags: ["#AutumnOmbre", "#FallBalayage", "#OmbreHair", "#WarmGradient", "#FallColors"] },
    { month: 9, day: 25, title: "Behind the Scenes: Consultation", description: "Show what happens during an extension consultation. Educate potential clients on the process.", category: "Behind the Scenes", contentType: "Video", hashtags: ["#ConsultationProcess", "#BehindTheScenes", "#WhatToExpect", "#ClientJourney", "#FirstStep"] },
    { month: 9, day: 27, title: "Weekend Vibes: Quick Styles", description: "Share quick weekend styling ideas for fall activities - apple picking, pumpkin patches, cozy dates.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#WeekendVibes", "#FallActivities", "#QuickStyles", "#SeasonalFun", "#EasyHair"] },
    { month: 9, day: 29, title: "October Booking Reminder", description: "Remind clients to book for October - busy season with fall events and Halloween preparations.", category: "Promotional", contentType: "Story", hashtags: ["#OctoberBooking", "#BookAhead", "#FallAppointments", "#DontWait", "#SecureYourSpot"] },
    { month: 9, day: 30, title: "September Transformation Gallery", description: "Compile the month's best fall transformations into a beautiful gallery celebrating the season.", category: "Before & After", contentType: "Carousel", hashtags: ["#SeptemberGallery", "#FallTransformations", "#MonthlyBest", "#AutumnHighlights", "#BeforeAfter"] },
    
    // October - Halloween, Fall Peak
    { month: 10, day: 1, title: "October Hair Magic", description: "Welcome October with enchanting fall hair inspiration. Embrace the magical, cozy vibes of the season.", category: "Inspiration", contentType: "Carousel", hashtags: ["#OctoberVibes", "#FallMagic", "#AutumnHair", "#CozyVibes", "#OctoberHair"] },
    { month: 10, day: 3, title: "Pumpkin Spice Hair Trend", description: "Feature the trending pumpkin spice hair color - warm oranges, coppers, and golden tones perfect for fall.", category: "Trending", contentType: "Reel", hashtags: ["#PumpkinSpiceHair", "#FallTrend", "#WarmCopper", "#TrendingColor", "#PSL"] },
    { month: 10, day: 5, title: "Halloween Costume Hair Ideas", description: "Share hair extension ideas for popular Halloween costumes. Show versatility and creative styling.", category: "Tips & Tricks", contentType: "Carousel", hashtags: ["#HalloweenHair", "#CostumeIdeas", "#HalloweenLook", "#CreativeHair", "#SpookyStyle"] },
    { month: 10, day: 7, title: "Fall Photoshoot Transformation", description: "Feature a gorgeous fall photoshoot transformation with autumnal backdrop and seasonal styling.", category: "Before & After", contentType: "Video", hashtags: ["#FallPhotoshoot", "#AutumnTransformation", "#SeasonalShoot", "#BeforeAfter", "#GorgeousFall"] },
    { month: 10, day: 9, title: "Breast Cancer Awareness", description: "Share supportive content for Breast Cancer Awareness Month. Highlight any charitable initiatives or pink-themed looks.", category: "Engagement", contentType: "Photo", hashtags: ["#BreastCancerAwareness", "#PinkOctober", "#Support", "#Awareness", "#PinkRibbon"] },
    { month: 10, day: 11, title: "Spooky Season Extension Care", description: "Fun tips on caring for extensions during Halloween season - protecting from costume makeup and accessories.", category: "Tips & Tricks", contentType: "Story", hashtags: ["#SpookySeason", "#HalloweenTips", "#ExtensionCare", "#CostumeSafe", "#ProtectYourHair"] },
    { month: 10, day: 13, title: "Friday the 13th Special", description: "Spooky special offer or fun content for Friday the 13th. Create themed engagement with followers.", category: "Promotional", contentType: "Photo", hashtags: ["#FridayThe13th", "#SpookySpecial", "#OctoberOffer", "#LuckyDeal", "#Superstitious"] },
    { month: 10, day: 15, title: "Client Spotlight: Halloween Ready", description: "Feature a client getting Halloween-ready with stunning extensions for their costume or event.", category: "Client Spotlight", contentType: "Reel", hashtags: ["#HalloweenReady", "#ClientFeature", "#CostumeGlam", "#SpookyTransformation", "#PartyReady"] },
    { month: 10, day: 17, title: "Temporary Color Extensions", description: "Showcase fun temporary color options with extensions - perfect for Halloween without permanent commitment.", category: "Product Showcase", contentType: "Carousel", hashtags: ["#TemporaryColor", "#FunHair", "#HalloweenColor", "#NoCommitment", "#PlayfulColor"] },
    { month: 10, day: 19, title: "Cozy Fall Styling Tutorial", description: "Create a tutorial for cozy, effortless fall styling - soft waves, gentle curls, and natural texture.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#CozyStyles", "#FallTutorial", "#SoftWaves", "#EffortlessHair", "#AutumnVibes"] },
    { month: 10, day: 21, title: "Behind the Scenes: Busy Season", description: "Show the excitement and energy of busy fall season at the salon. Celebrate the teamwork.", category: "Behind the Scenes", contentType: "Video", hashtags: ["#BusySeason", "#SalonEnergy", "#BehindTheScenes", "#TeamWork", "#FallRush"] },
    { month: 10, day: 23, title: "Dark & Dramatic Fall Looks", description: "Feature dark, dramatic hair transformations perfect for the moody fall aesthetic.", category: "Before & After", contentType: "Carousel", hashtags: ["#DarkHair", "#DramaticLook", "#MoodyVibes", "#FallAesthetic", "#BoldTransformation"] },
    { month: 10, day: 25, title: "Halloween Week Countdown", description: "Start the Halloween countdown with daily spooky-themed hair content and styling ideas.", category: "Engagement", contentType: "Story", hashtags: ["#HalloweenCountdown", "#SpookyWeek", "#HalloweenWeek", "#CountdownBegins", "#GetReady"] },
    { month: 10, day: 27, title: "Last-Minute Halloween Styles", description: "Quick, last-minute hair styling ideas for Halloween parties and events. Easy yet impactful looks.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#LastMinute", "#HalloweenStyles", "#QuickLooks", "#PartyReady", "#EasyGlam"] },
    { month: 10, day: 29, title: "Halloween Transformation Reveal", description: "Dramatic Halloween-themed transformation reveal. Build suspense and excitement.", category: "Before & After", contentType: "Reel", hashtags: ["#HalloweenTransformation", "#SpookyReveal", "#DramaticChange", "#BeforeAfter", "#HalloweenGlam"] },
    { month: 10, day: 31, title: "Happy Halloween", description: "Celebrate Halloween with festive wishes and showcase of the day's amazing looks and costumes.", category: "Engagement", contentType: "Carousel", hashtags: ["#HappyHalloween", "#Halloween2025", "#SpookyDay", "#TrickOrTreat", "#HalloweenFun"] },
    
    // November - Thanksgiving, Gratitude
    { month: 11, day: 1, title: "November Gratitude Month", description: "Welcome November with gratitude themes. Begin sharing what you're thankful for in your hair journey.", category: "Inspiration", contentType: "Photo", hashtags: ["#NovemberGratitude", "#ThankfulMonth", "#Grateful", "#NovemberVibes", "#Thankful"] },
    { month: 11, day: 3, title: "Cozy Fall Transformations", description: "Feature warm, cozy fall transformations perfect for sweater weather and holiday preparations.", category: "Before & After", contentType: "Carousel", hashtags: ["#CozyFall", "#SweaterWeather", "#WarmVibes", "#FallTransformation", "#ComfortColors"] },
    { month: 11, day: 5, title: "Election Day Style", description: "Encourage civic engagement while sharing polished, confident looks for election day.", category: "Inspiration", contentType: "Story", hashtags: ["#ElectionDay", "#Vote", "#ConfidentLook", "#CivicDuty", "#MakeYourVoiceHeard"] },
    { month: 11, day: 7, title: "Holiday Hair Prep Guide", description: "Create a comprehensive guide for preparing hair and extensions for the holiday season ahead.", category: "Educational", contentType: "Carousel", hashtags: ["#HolidayPrep", "#HolidayHair", "#GetReady", "#SeasonalGuide", "#HolidayPlanning"] },
    { month: 11, day: 9, title: "Client Appreciation Week", description: "Begin client appreciation week with special thank-you content and exclusive offers for loyal clients.", category: "Promotional", contentType: "Photo", hashtags: ["#ClientAppreciation", "#ThankYouClients", "#Loyalty", "#Gratitude", "#SpecialOffer"] },
    { month: 11, day: 11, title: "Veterans Day Tribute", description: "Honor Veterans Day with respectful tribute and appreciation for those who served.", category: "Engagement", contentType: "Photo", hashtags: ["#VeteransDay", "#ThankYouVeterans", "#Honor", "#Respect", "#VeteranAppreciation"] },
    { month: 11, day: 13, title: "Thanksgiving Hair Inspiration", description: "Share Thanksgiving-ready hairstyles - elegant yet practical for cooking, hosting, and celebrating.", category: "Inspiration", contentType: "Carousel", hashtags: ["#ThanksgivingHair", "#HolidayStyle", "#FamilyGathering", "#FestiveHair", "#TurkeyDay"] },
    { month: 11, day: 15, title: "Extension Method: Sew-Ins", description: "Educate on sew-in extension method - ideal candidates, process, care, and benefits.", category: "Educational", contentType: "Video", hashtags: ["#SewInExtensions", "#ExtensionMethod", "#HairEducation", "#SewInBenefits", "#ProtectiveStyle"] },
    { month: 11, day: 17, title: "Thanksgiving Prep Transformation", description: "Feature a client getting ready for Thanksgiving with a beautiful, festive transformation.", category: "Before & After", contentType: "Reel", hashtags: ["#ThanksgivingPrep", "#HolidayReady", "#BeforeAfter", "#FestiveTransformation", "#GatheringReady"] },
    { month: 11, day: 19, title: "Cold Weather Hair Care", description: "Essential tips for protecting extensions during cold weather - indoor heating, dry air, and static.", category: "Tips & Tricks", contentType: "Carousel", hashtags: ["#ColdWeatherCare", "#WinterTips", "#DryAir", "#StaticFree", "#SeasonalCare"] },
    { month: 11, day: 21, title: "Thanksgiving Week Countdown", description: "Begin Thanksgiving week countdown with gratitude posts and holiday hair inspiration.", category: "Engagement", contentType: "Story", hashtags: ["#ThanksgivingCountdown", "#HolidayWeek", "#Grateful", "#FamilyTime", "#Celebration"] },
    { month: 11, day: 23, title: "Black Friday Preview", description: "Tease upcoming Black Friday deals and specials. Create anticipation for holiday shopping.", category: "Promotional", contentType: "Story", hashtags: ["#BlackFridayPreview", "#ComingSoon", "#HolidayDeals", "#StayTuned", "#BigSale"] },
    { month: 11, day: 25, title: "Happy Thanksgiving", description: "Share heartfelt Thanksgiving wishes with your community. Express gratitude for clients and followers.", category: "Engagement", contentType: "Photo", hashtags: ["#HappyThanksgiving", "#Grateful", "#ThankfulForYou", "#FamilyTime", "#ThanksgivingDay"] },
    { month: 11, day: 27, title: "Black Friday Sale", description: "Announce Black Friday deals on extension services, products, and gift cards.", category: "Promotional", contentType: "Carousel", hashtags: ["#BlackFriday", "#BlackFridaySale", "#HolidayDeals", "#ShopNow", "#BiggestSale"] },
    { month: 11, day: 29, title: "Small Business Saturday", description: "Celebrate Small Business Saturday with appreciation for local support and special offers.", category: "Promotional", contentType: "Photo", hashtags: ["#SmallBusinessSaturday", "#ShopSmall", "#LocalLove", "#SupportLocal", "#SmallBusiness"] },
    { month: 11, day: 30, title: "November Gratitude Recap", description: "Conclude November with a gratitude recap - favorite moments, client wins, and thankful reflections.", category: "Before & After", contentType: "Carousel", hashtags: ["#NovemberRecap", "#GratitudeMonth", "#ThankfulReview", "#BestMoments", "#EndOfMonth"] },
    
    // December - Holidays, New Year Prep
    { month: 12, day: 1, title: "December Magic Begins", description: "Welcome December with holiday magic and festive hair inspiration. Kick off the most wonderful time of the year.", category: "Inspiration", contentType: "Carousel", hashtags: ["#DecemberMagic", "#HolidaySeason", "#FestiveVibes", "#HelloDecember", "#WonderfulTime"] },
    { month: 12, day: 3, title: "Holiday Party Hair Guide", description: "Comprehensive guide to holiday party hairstyles using extensions - from office parties to black-tie events.", category: "Tips & Tricks", contentType: "Carousel", hashtags: ["#HolidayPartyHair", "#PartyStyle", "#FestiveGlam", "#EventHair", "#CelebrationReady"] },
    { month: 12, day: 5, title: "Glamorous Holiday Transformation", description: "Feature a stunning holiday transformation - sparkle, glamour, and festive elegance.", category: "Before & After", contentType: "Reel", hashtags: ["#HolidayTransformation", "#GlamHair", "#FestiveGlam", "#BeforeAfter", "#SparkleAndShine"] },
    { month: 12, day: 7, title: "Gift Guide: Hair Lover Edition", description: "Create a gift guide for hair lovers - extension services, care products, tools, and accessories.", category: "Promotional", contentType: "Carousel", hashtags: ["#GiftGuide", "#HairLoverGifts", "#HolidayGifts", "#GiftIdeas", "#TreatYourself"] },
    { month: 12, day: 9, title: "Winter Hair Protection", description: "Essential tips for protecting extensions during winter - cold, wind, hats, and dry indoor heat.", category: "Educational", contentType: "Carousel", hashtags: ["#WinterHairCare", "#ColdWeatherTips", "#ProtectYourHair", "#SeasonalCare", "#WinterReady"] },
    { month: 12, day: 11, title: "12 Days of Hair Tips", description: "Begin a 12-day series sharing daily hair tips, tricks, and inspiration leading up to the holidays.", category: "Tips & Tricks", contentType: "Story", hashtags: ["#12DaysOfHair", "#DailyTips", "#HolidayCountdown", "#HairAdvice", "#TipSeries"] },
    { month: 12, day: 13, title: "Client Spotlight: Holiday Glam", description: "Feature clients getting holiday-ready with gorgeous transformations for the festive season.", category: "Client Spotlight", contentType: "Carousel", hashtags: ["#HolidayGlam", "#ClientFeature", "#FestiveTransformation", "#PartyReady", "#HolidayBeauty"] },
    { month: 12, day: 15, title: "Last-Minute Holiday Appointments", description: "Reminder for last-minute holiday appointment availability. Create urgency for bookings.", category: "Promotional", contentType: "Story", hashtags: ["#LastMinuteAppointments", "#HolidayBooking", "#BookNow", "#LimitedSlots", "#DontMissOut"] },
    { month: 12, day: 17, title: "Festive Styling Tutorial", description: "Create a tutorial for elegant holiday styling - sleek updos, voluminous curls, or glamorous waves.", category: "Tips & Tricks", contentType: "Reel", hashtags: ["#FestiveStyling", "#HolidayTutorial", "#GlamStyles", "#HolidayHair", "#DIYStyle"] },
    { month: 12, day: 19, title: "Year in Review: Best Transformations", description: "Begin the year-end review with the year's most stunning transformations and memorable moments.", category: "Before & After", contentType: "Carousel", hashtags: ["#YearInReview", "#BestOf2025", "#TopTransformations", "#YearHighlights", "#AmazingWork"] },
    { month: 12, day: 21, title: "Winter Solstice Celebration", description: "Celebrate the winter solstice with cozy, magical content marking the shortest day of the year.", category: "Inspiration", contentType: "Photo", hashtags: ["#WinterSolstice", "#ShortestDay", "#CozyVibes", "#WinterMagic", "#SolsticeCelebration"] },
    { month: 12, day: 23, title: "Christmas Eve Prep", description: "Last-minute styling tips and inspiration for Christmas Eve celebrations and gatherings.", category: "Tips & Tricks", contentType: "Story", hashtags: ["#ChristmasEvePrep", "#HolidayReady", "#LastMinuteStyle", "#FamilyGathering", "#CelebrationReady"] },
    { month: 12, day: 25, title: "Merry Christmas", description: "Share warm Christmas wishes with your community. Celebrate the joy of the holiday season.", category: "Engagement", contentType: "Photo", hashtags: ["#MerryChristmas", "#HappyHolidays", "#ChristmasJoy", "#HolidayLove", "#SeasonGreetings"] },
    { month: 12, day: 27, title: "New Year's Eve Hair Ideas", description: "Share stunning New Year's Eve hairstyle ideas - glamorous, sparkly, and celebration-worthy looks.", category: "Inspiration", contentType: "Carousel", hashtags: ["#NYEHair", "#NewYearsEve", "#PartyHair", "#CelebrationStyle", "#GlamNight"] },
    { month: 12, day: 29, title: "Year End Gratitude", description: "Express gratitude for the year's journey, clients, and community. Reflect on growth and achievements.", category: "Engagement", contentType: "Carousel", hashtags: ["#YearEndGratitude", "#ThankYou2025", "#Grateful", "#CommunityLove", "#YearReflection"] },
    { month: 12, day: 31, title: "Happy New Year", description: "Celebrate New Year's Eve with festive wishes and excitement for the year ahead. Share goals and hopes for the new year.", category: "Engagement", contentType: "Photo", hashtags: ["#HappyNewYear", "#NewYear2026", "#Celebrate", "#NewBeginnings", "#Cheers"] },
  ];
  
  for (let i = 0; i < contentData.length; i++) {
    const data = contentData[i];
    posts.push({
      id: `post-${i + 1}`,
      date: `2025-${String(data.month).padStart(2, '0')}-${String(data.day).padStart(2, '0')}`,
      month: data.month,
      day: data.day,
      title: data.title,
      description: data.description,
      category: data.category as any,
      contentType: data.contentType as any,
      hashtags: data.hashtags,
    });
  }
  
  return posts;
}

export class MemStorage implements IStorage {
  private posts: Map<string, Post>;

  constructor() {
    this.posts = new Map();
    const initialPosts = generateHairExtensionContent();
    initialPosts.forEach(post => this.posts.set(post.id, post));
  }

  async getAllPosts(): Promise<Post[]> {
    return Array.from(this.posts.values()).sort((a, b) => {
      if (a.month !== b.month) return a.month - b.month;
      return a.day - b.day;
    });
  }

  async getPostsByMonth(month: number): Promise<Post[]> {
    return Array.from(this.posts.values())
      .filter(post => post.month === month)
      .sort((a, b) => a.day - b.day);
  }

  async getPostById(id: string): Promise<Post | undefined> {
    return this.posts.get(id);
  }
}

export const storage = new MemStorage();
